### ISSUE TITLE
Search API Solr cannot connect to Pantheon Solr

### ISSUE THREAD

**Issue by ioskevich** [pantheon-systems/drops-7#110]
Tested using:

- search_api 7.x-1.21 + search_api_solr 7.x-1.2
- pantheon_apache_solr 7.x-1.0

and 

- search_api 7.x-1.22 + search_api_solr 7.x-1.12
- pantheon_apache_solr 7.x-1.0

Solr Schema 3.x from search_api_solr posted to Pantheon.
pantheon_apache_solr status says Solr server is available and is responding to ping command.

Issues:

1. **Issue 1**: Search API Solr server values are not overridden with pantheon_apache_solr
2. **Issue 2**: Once Solr server config is adjusted manually using values deducted from pantheon_apache_solr module, Search API still reports Solr server as unavailable.
3. **Issue 3**: Docs page (https://pantheon.io/docs/solr-drupal-7/) requires update - at least mentioning that Search API Solr integration is not working currently (at least for specific versions of the modules above)

Issue 2 is caused by the function makeHttpRequest() (in Pantheon_Search_Api_Solr_Service.php) not using SSL certificate when connecting to Pantheon Solr. 

Temporary workaround for Issue 2 for me was to replace contents of makeHttpRequest() in Pantheon_Search_Api_Solr_Service.php with the contents of _makeHttpRequest() from  Pantheon_Apache_Solr_Service.php

Looking at the pantheon_apache_solr module (current HEAD of master) in general, it seems that it was updated at certain point to be compatible with apache_solr module, but search_api_solr integration was left as is and definitely requires refactoring.

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
