### ISSUE TITLE
Update pantheon_api module API calls

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/drops-7#112]
https://github.com/pantheon-systems/drops-7/blob/master/modules/pantheon/pantheon_api/pantheon_api.module#L20L21

Seems like pantheon_bulk_file_delete() has been retired (internal reference: dts comment in BUGS-1599)

**Comment by tinefin** [comment]
It would be great if we can remove this.
When debugging slow image style clearing, this function naturally gets a lot of attention as it is a "core hack". In reality it's a "red herring" as it really doesn't do anything anymore.
But it is a tough (!) explanation / time consuming conversation, since usually core hacks are only in place if there is a super important reason for it.

**Comment by eabquina** [comment]
One customer tested to remove this in the repo and it worked for them.
#4497 
Referencing code snippet from customer
https://github.com/pantheon-systems/documentation/issues/4497

**Comment by jdleonard** [comment]
Why oh why does pantheon_api_image_path_flush() still exist if it will never be called?

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
