### ISSUE TITLE
http ajax error 403 when indexing with search api

### ISSUE THREAD

**Issue by ugintl** [pantheon-systems/drops-7#116]
I have configured dbserver on search api. I am trying to index profile2 data. I am on pantheon. I have tried few things. I removed the server and added again and re-enabled. Then I tried to index 1 item. Then I downgraded my jquery to 1.4. Nothing worked. This is the error `An AJAX HTTP error occurred. HTTP Result Code: 403 Debugging information follows. Path: /batch?id=102&op=do StatusText: Forbidden ResponseText: 403 error | Commerce Kickstart @import url("http://dev-resumebrowse.pantheonsite.io/modules/system/system.base.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/modules/system/system.menus.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/modules/system/system.messages.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/modules/system/system.theme.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/modules/system/system.admin.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/modules/comment/comment.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/modules/contrib/date/date_api/date.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/modules/contrib/date/date_popup/themes/datepicker.1.7.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/modules/contrib/fences/field.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/modules/node/node.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/modules/user/user.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/modules/contrib/views/css/views.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/modules/contrib/colorbox/styles/default/colorbox_style.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/modules/contrib/ctools/css/ctools.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/modules/contrib/panels/css/panels.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/modules/contrib/wysiwyg_linebreaks/wysiwyg_linebreaks.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/themes/contrib/shiny/css/reset.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/themes/contrib/shiny/css/style.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/themes/contrib/shiny/css/contrib.css?p5krf0"); @import url("http://dev-resumebrowse.pantheonsite.io/profiles/commerce_kickstart/themes/contrib/shiny/css/shiny.css?p5krf0"); Skip to main content 403 error Home 403 error Access denied `

**Comment by davidstrauss** [comment]
This is probably unrelated to the drops-7 repository, so I'm closing this. Please feel free to reach out to our support resources (chat, tickets, Power Users group) if you still need help.
