### ISSUE TITLE
Update core per PSA-2018-001

### ISSUE THREAD

**Issue by chrisgross** [pantheon-systems/drops-7#118]
According to [PSA-2018-001](https://www.drupal.org/psa-2018-001), there will be a critical security update released today. Lately, updates to core don't ever seem to get pushed to this repo until someone creates an issue. Can we make sure this one gets done ASAP?

**Comment by joshkoenig** [comment]
We make all security updates available regardless of there being an issue. For this release we have engineers standing by on call to make sure this update will be available immediately.
