### ISSUE TITLE
After enabling Pantheon Apache Solr: "Notice: Undefined index: name in search_api_help()"

### ISSUE THREAD

**Issue by GuyPaddock** [pantheon-systems/drops-7#120]
I have Search API already installed, but am enabling Pantheon Apache Solr for the first time on this instance. It looks like until the schema is posted, this PHP notice appears on every cache clear:

```
Notice: Undefined index: name in search_api_help() (line 188 of /srv/bindings/c7df118083a04f74bf4227b9cb4dc66e/code/sites/default/modules/contrib/search/search_api/search_api.module).
```

I am using Search API 1.22.

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
