### ISSUE TITLE
common.inc.orig file committed as part of Drupal 7.61 update

### ISSUE THREAD

**Issue by joeparsons** [pantheon-systems/drops-7#136]
An extra file, `includes/common.inc.orig`, was committed to this repo as part of the recent 7.61 update.  I imagine this is a leftover/cruft file created while git was merging the upstream drupal.org changes to `common.inc` and was not added intentionally.

**Comment by greg-1-anderson** [comment]
Yes, you are correct. The file was created when the `patch` tool was called with the incorrect flags. The update tool has been fixed; this file will be removed in the next release.

**Comment by joeparsons** [comment]
OK, cool.  Feel free to disregard my PR, then.
