### ISSUE TITLE
Merge Conflict Updating to 7.71 with One-Click and Pull

### ISSUE THREAD

**Issue by danheisel** [pantheon-systems/drops-7#157]
Hi. I am running through and updating some sites to 7.71. Normally, the one-click method does just fine. However, we're now hitting merge conflicts using this method to update core. The conflicts from one-click are:

`CONFLICT (content): Merge conflict in scripts/run-tests.sh,CONFLICT (content): Merge conflict in modules/taxonomy/taxonomy.install,CONFLICT (content): Merge conflict in modules/system/system.test,CONFLICT (content): Merge conflict in modules/simpletest/simpletest.info,CONFLICT (content): Merge conflict in modules/search/search.module,CONFLICT (content): Merge conflict in modules/search/search.extender.inc,CONFLICT (content): Merge conflict in modules/forum/forum.module,CONFLICT (content): Merge conflict in modules/filter/filter.api.php,CONFLICT (content): Merge conflict in modules/field_ui/field_ui.module,CONFLICT (content): Merge conflict in modules/field_ui/field_ui.admin.inc,CONFLICT (content): Merge conflict in modules/field/tests/field_test.storage.inc,CONFLICT (content): Merge conflict in modules/field/modules/number/number.test,CONFLICT (content): Merge conflict in modules/comment/comment.test,CONFLICT (content): Merge conflict in modules/comment/comment.install,CONFLICT (content): Merge conflict in modules/color/color.module,CONFLICT (content): Merge conflict in modules/block/block.module,CONFLICT (content): Merge conflict in misc/typo3/phar-stream-wrapper/src/Resolver/PharInvocationResolver.php,CONFLICT (content): Merge conflict in misc/typo3/phar-stream-wrapper/src/PharStreamWrapper.php,CONFLICT (content): Merge conflict in misc/typo3/phar-stream-wrapper/src/Phar/Reader.php,CONFLICT (content): Merge conflict in misc/typo3/phar-stream-wrapper/src/Helper.php,CONFLICT (content): Merge conflict in misc/typo3/phar-stream-wrapper/composer.json,CONFLICT (content): Merge conflict in misc/typo3/phar-stream-wrapper/README.md,CONFLICT (modify/delete): misc/typo3/phar-stream-wrapper/.gitignore deleted in upstream/master and modified in HEAD. Version HEAD of misc/typo3/phar-stream-wrapper/.gitignore left in tree.,CONFLICT (content): Merge conflict in misc/ajax.js,CONFLICT (content): Merge conflict in includes/request-sanitizer.inc,CONFLICT (content): Merge conflict in includes/path.inc,CONFLICT (content): Merge conflict in includes/menu.inc,CONFLICT (content): Merge conflict in includes/filetransfer/filetransfer.inc,CONFLICT (content): Merge conflict in includes/batch.inc`

As an alternative, I ran **git pull -Xtheirs git://github.com/pantheon-systems/drops-7.git master** locally and everything updated except for **misc/typo-3/phar-stream-wrapper/.gitignore**. Looks like that file was deleted in the Drops-7 repository but my local copy remained. Removing the file and pushing the local changes up to my site seemed to work just fine. Just curious if I'm the only one seeing this with the latest update. Thanks!

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
