### ISSUE TITLE
Search form error on submit caused by setting $search_default_module to apachesolr_search

### ISSUE THREAD

**Issue by suzannealdrich** [pantheon-systems/drops-7#58]
On vanilla install of drops-7, the Pantheon profile sets sets $search_default_module to apachesolr_search and disables the core node search as a default:

https://github.com/pantheon-systems/drops-7/blob/ea54cb1d6318517582e7258e880ce02ab5a2cbfd/profiles/pantheon/pantheon.profile

```
  $search_active_modules = array(
    'apachesolr_search' => 'apachesolr_search',
    'user' => 'user',
    'node' => 0
  );
  variable_set('search_active_modules', $search_active_modules);
  variable_set('search_default_module', 'apachesolr_search');
  drupal_set_message(t('Pantheon defaults configured.'));
```

However we don't enable the Pantheon ApacheSolr module by default:

https://github.com/pantheon-systems/drops-7/blob/ea54cb1d6318517582e7258e880ce02ab5a2cbfd/profiles/pantheon/pantheon.info

```
  ;dependencies[] = apachesolr
;dependencies[] = apachesolr_search
dependencies[] = pantheon_api
dependencies[] = pantheon_login
;dependencies[] = pantheon_apachesolr
```

So when a user with permission loads /admin/config/search/settings to setup indexing for their site using the core search module, neither the node nor user radio button is selected, if they save the form without selecting one, they get the error message "An illegal choice has been detected. Please contact the site administrator." They must first enable one or both of the checkboxes and then select a radio button, for this form to submit without error:

https://github.com/pantheon-systems/drops-7/blob/master/modules/search/search.admin.inc

```
  $form['active']['search_active_modules'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Active modules'),
    '#title_display' => 'invisible',
    '#default_value' => variable_get('search_active_modules', array('node', 'user')),
    '#options' => $module_options,
    '#description' => t('Choose which search modules are active from the available modules.')
  );
  $form['active']['search_default_module'] = array(
    '#title' => t('Default search module'),
    '#type' => 'radios',
    '#default_value' => variable_get('search_default_module', 'node'),
    '#options' => $module_options,
    '#description' => t('Choose which search module is the default.')
```

At the time of profile installation, the default should remain the core node search, and not be wiped out on installation of this profile, so users who are trying to configure core search can have a good experience trying to submit the form.

**Comment by jpilcher** [comment]
Enabling the module allows you to submit the search settings form. Then going back and disabling the module appears for me at least to allow the search settings to still function normally.

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
