### ISSUE TITLE
Path issue on pantheon_api_image_path_flush()

### ISSUE THREAD

**Issue by AtlantaJones** [pantheon-systems/drops-7#59]
I had created a support ticket from my dashboard a couple days ago regarding a module for image cropping that wasn't working (https://www.drupal.org/project/focal_point). It wasn't working after the initial crop, as any subsequent crop wasn't taking effect. I had suspected maybe something with Varnish was keeping the image from being updated.

Turns out, there seems to be a problem with the pantheon_api_image_path_flush() hook within /modules/pantheon/pantheon_api/pantheon_api.module. 

I simply changed this:
`$paths[] = file_uri_target($image_path);`

to this:
`$paths[] = '/' . file_uri_target($image_path);`

... and it started working. I was told that this had been moved to Pantheon's "internal tracker", so I wasn't sure where to post this fix. I could also possibly submit a pull request if necessary.

**Comment by kstangel** [comment]
Was this fixed? I am seeing the same issue in D8.

**Comment by greg-1-anderson** [comment]
This [has been fixed in drops-7](https://github.com/pantheon-systems/drops-7/blame/master/modules/pantheon/pantheon_api/pantheon_api.module#L38). Drops-8 does not have an image path flush hook; any problems with image-related modules on Drupal 8 must have a different cause.
