### ISSUE TITLE
Pantheon Apache Solr Execute Query Syntax

### ISSUE THREAD

**Issue by nexttee** [pantheon-systems/drops-7#67]
Hello,

I’m trying to figure out how to test the solr index on the Execute Query page.
I found this document, http://coder1.com/articles/analyze-your-solr-index-pantheon
but this syntax isn’t working with the Pantheon Execute Query.

I'd like to see the type and title of the content, but the syntax doesn't let that happen.

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
