### ISSUE TITLE
Write permission to custom folder

### ISSUE THREAD

**Issue by doodirock** [pantheon-systems/drops-7#69]
I have a folder in pantheon on our dev environment that is writable by a script that create temporary files.  It's not drupal related to much in the sense that it takes a drupal RSS feed and converts it to MRSS and creates a temp file in this folder.  

In dev this folder works fine. I'm about to write to it without issue and destroy the contents later.  However once i push to test and live I get write permissions issues.  I'm assuming this has something to do with SFTP mode, but the fact that both environments don't act the same makes developing a pain.  

My question is, are we able to have writable folders within test and live that live outside of drupal?  If not how would someone handle this type of need?  I don't want to have to setup an outside resource for something this simple.

**Comment by greg-1-anderson** [comment]
In 'git' mode, most locations are write-protected.  As you observed, in 'sftp' mode, it is possible to write to any location in a 'dev' or 'multidev' environment.  However, the 'test' and 'live' environments are essentially permanently in 'git' mode.  You should therefore write your temporary files to a location that is guaranteed to be writable.

You can find the location of the temporary directory for Drupal 7 via the API function [file_directory_temp](https://api.drupal.org/api/drupal/includes%21file.inc/function/file_directory_temp/7).

**Comment by doodirock** [comment]
Is there a way to do this outside of drupal?  The script is really only a few lines of code and doesnt/shouldnt really need to live inside of drupal.  Can i get a path to a writable area without drupal?

**Comment by doodirock** [comment]
Maybe something like dirname($_SERVER['DOCUMENT_ROOT']).'/files';

**Comment by doodirock** [comment]
Looks like this worked.   Thanks
