### ISSUE TITLE
.gitignore entry causing module issues

### ISSUE THREAD

**Issue by jrisebor** [pantheon-systems/drops-7#72]
the "Icon" entry in the .gitignore file is causing the following module to not be included:

https://www.drupal.org/project/icon

**Comment by greg-1-anderson** [comment]
I can't reproduce this on MacOS.  What OS are you using?

When I view the .gitignore file in vi, I see that the "Icon" entry is actually "Icon^M^M", which is [what is recommended](http://stackoverflow.com/questions/17556250/how-to-ignore-icon-in-git).  Check your .gitignore file, and see if perhaps it was somehow translated to some other form (e.g. trailing ^Ms removed).

On my system, if I download the icon project, it shows up as untracked in 'git status'.

**Comment by jrisebor** [comment]
This is on Mac OSX using PHPStorm. After doing some testing, it seems like this is an issue with phpstorm removing the trailing "^M^M" when editing the .gitignore file.
