### ISSUE TITLE
drush command for posting solr schema

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/drops-7#82]
There is a Power Users thread for posting Solr schema upon multidev creation: https://groups.google.com/a/pantheon.io/forum/#!topic/power-users/sowAXap1bOk

While the "upon multidev creation" is likely out of the scope of this repo, the posting itself could be made more scriptable with a drush command.

I'm thinking of a command that could be invoked like `drush pantheon-apachesolr-post-schema --schema=sites/all/modules/contrib/apachesolr/solr-conf/solr-3.x/schema.xml`

The drush piece would be relatively simple, just a wrapper around `pantheon_apachesolr_post_schema_exec()`

@greg-1-anderson, can I get your thoughts before I proceed with writing the drush command?

**Comment by greg-1-anderson** [comment]
Sounds good to me. We don't quite have [modern cli commands](https://pantheon.io/blog/modern-command-line-tools-drupal-modules-drush-and-drupal-console) deployed yet, so a traditional Drush command would probably be best.

**Comment by ordavidil** [comment]
any updates on this one ?
:\

**Comment by stevector** [comment]
PR over here: https://github.com/pantheon-systems/drops-7/pull/99

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
