### ISSUE TITLE
Permission issue.

### ISSUE THREAD

**Issue by jucallme** [pantheon-systems/drops-7#83]
Not every site has drupal core search enabled. Yet this module depends on permissions that are set in that to access the admin page of the pantheon admin screen. There is not even a dependancy mentioned in the info file of the module... yet it requires the 'administer search' permission be set @see pantheon_apachesolr_menu.

Either add a dependancy to the core search, or create your own permission. The second option is better as not every one running solr search has core search enabled. and fix documentation at https://pantheon.io/docs/solr-drupal/

**Comment by greg-1-anderson** [comment]
Is this a duplicate of #43?  If so, please see if https://github.com/pantheon-systems/drops-7/pull/76 resolves your issue.

**Comment by jucallme** [comment]
Yes this is a duplicated then thanks for the patch on the other ticket awaiting this fix for some time now.
