### ISSUE TITLE
Add Circle CI tests

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/drops-7#97]
We have tests running on pull request for some of our major repositories like https://github.com/pantheon-systems/drops-8 and https://github.com/pantheon-systems/WordPress. Adding similar tests here to verify installation and basic administrative tasks will give us more confidence in merging pull requests.

**Comment by stevector** [comment]
@greg-1-anderson, I have a solid start here https://github.com/stevector/drops-7 and here https://github.com/stevector/ci-drops-7

My fork of drops-7 uses just the Circle UI (no `circle.yml` added). It clones in ci-drops-7 which provides the Behat tests.

ci-drops-7 has it's own [circle.yml](https://github.com/stevector/ci-drops-7/blob/master/circle.yml) file which is pretty simple too.

One of the nice features is aligning PRs between the two. So a branch on drops-7 will check for a branch of the same name in ci-drops-7 and vice versa. For example both repos have a branch name `solr_drush`.  See https://github.com/stevector/drops-7/pull/2 and https://github.com/stevector/ci-drops-7/pull/3

There's no rush on porting these over to `pantheon-systems`. I know it is an upcoming ticket for you. When you get to it, you probably will want to add more actual tests to `ci-drops-7`. Right now the only real test is of adding users. I also deleted a lot of files from `ci-drops-7` after forking from `ci-drops-8` just so that I was clear on what was being used and what wasn't. Feel free to add back/change whatever you want.

**Comment by greg-1-anderson** [comment]
Looks great -- super helpful! If you've done enough to satisfy your current needs, feel free to move on to something else, and I'll add more tests when I pick up the card later this week. On the flip side, don't hold yourself back if you want to push this further forward. I won't feel bad if I just have to write "Steve did this already" on the Jira card. 😉

**Comment by stevector** [comment]
I should probably stop here. Will making another repo for common Behat steps be part of that card or is that scope creep?

**Comment by greg-1-anderson** [comment]
I probably won't get to that, but we'll see how much time I have at the end of the sprint.

**Comment by scottbuscemi** [comment]
Closing as stale. Please re-open if needed.
